base/urls.py
from base.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', home, name="home"),
    path('about', about, name="about"),
    path('services', services, name="services"),
    path('contact', contact, name="contact"),
    path('logout/', logout_view, name="logout"),  # Logout route

    ##Authentication urls
    path('login/', login_view, name="login"),
    path('register/', register, name='register'),
    ##Admin urls
    path('admin-dashboard/', admin_dashboard, name="admin_dashboard"),
    path('admin-show/', admin_show, name="admin_show"),
    path('approved-students/', approved_students, name="approved_students"),
    path('rejected-students/', rejected_students, name="rejected_students"),
    ##Students urls
    path('student-detail/<int:student_id>/', student_detail, name="student_detail"),
    path('student-dashboard/', home, name="student_dashboard"),
]

ed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),  # Add base app URLs
]

templates/inc/admin_sidebar.html
<div class="col-xl-3 col-lg-4">
    <div class="card user-sidebar mb-4">
        <div class="card-header user-sidebar-header">
            <div class="profile-content rounded-pill">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="d-flex align-items-center justify-content-center py-2">
                        <img src="assets/imgs/section-1/img-2.png" alt="image" class="img-fluid avatar avatar-lg rounded-circle me-3">
                        <div>
                            <p class="fw-bold fs-5">Admin</p>
                            <span class="fs-14 text-gray-6">Admin Dashboard</span>
                        </div>
                        {% comment %} <div>
                            <p class="fw-bold fs-5">{{ request.user.role|title }}</p>  <!-- Shows 'Admin' or 'Student' -->
                            <span class="fs-14 text-gray-6">{{ request.user.full_name }}</span>  <!-- Displays Full Name -->
                        </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body user-sidebar-body">
            <ul class="dashboard-sidebar-menu">
                <li class="py-2">
                    <a href="{% url 'base:admin_dashboard' %}">
                        <i class="fi fi-rr-home me-1 text-primary"></i> Dashboard
                    </a>
                </li>
                <li class="py-2">
                    <a href="{% url 'base:admin_show' %}">
                        <i class="fi fi-rr-hourglass-end me-1 text-warning"></i> Pending Students
                    </a>
                </li>
                <li class="py-2">
                    <a href="{% url 'base:approved_students' %}">
                        <i class="fi fi-rr-check me-1 text-success"></i> Approved Students
                    </a>
                </li>
                <li class="py-2">
                    <a href="{% url 'base:rejected_students' %}">
                        <i class="fi fi-rr-cross-circle me-1 text-danger"></i> Rejected Students
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/inc/footer.html
{% load static %}

<footer class="footer">
    <div class="container">
        <div class="footer-top">
            <div class="row align-items-center">
                <div class="col-lg-5 col-md-6 text-center text-md-start">
                    <h5 class="color-white wow fadeInDown">Subscribe to our newsletter</h5>
                </div>
                <div class="col-lg-7 col-md-6 text-center text-md-end mt-md-0 mt-4">
                    <div class="d-flex align-items-center justify-content-center justify-content-md-end">
                        <form class="form-newsletter wow fadeInUp" action="#">
                            <input class="form-control" type="text" placeholder="Enter your email"/>
                            <input class="btn btn-brand-2" type="submit" value="Subscribe"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-12 footer-1">
                <div class="mt-20 mb-20">
                    <a class="d-flex" href="{% url 'base:home' %}">
                        <img class="light-mode" alt="SAF" src="{% static 'img/logo/logo-green.png' %}" style="width: 100px;"/>
                        <img class="dark-mode" alt="SAF" src="{% static 'img/logo/logo-green.png' %}" style="width: 100px;"/>
                    </a>
                    <div class="box-info-contact mt-0">
                        <p class="text-md neutral-400 icon-address">Location</p>
                        <p class="text-md neutral-400 icon-email">info@sfa.com</p>
                    </div>
                    <div class="box-need-help">
                        <p class="need-help text-md-medium mb-5">Need help? Call us</p>
                        <br/>
                        <a class="heading-6 phone-support" href="tel:+250 712 345 678">+250 712 345 678</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 footer-3">
                <h6 class="text-linear-3">About Us</h6>
                <ul class="menu-footer">
                    <li><a href="#" class="fw-bold">Our Story</a></li>
                    <li><a href="#" class="fw-bold">Our Mission</a></li>
                    <li><a href="#" class="fw-bold">The Impact</a></li>
                    <li><a href="#" class="fw-bold">Meet Our Team</a></li>
                    <li><a href="#" class="fw-bold">Blog</a></li>
                    <li><a href="#" class="fw-bold">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-md-2 col-xs-6 footer-2">
                <h6 class="text-linear-3">What We Do</h6>
                <ul class="menu-footer">
                    <li><a href="#" class="fw-bold">Connecting People</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom mt-50">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-6 text-md-start text-center mb-20">
                    <p class="text-sm color-white">© 2025 Kigali Nanny Agency Inc. All rights reserved.</p>
                </div>
                <div class="col-md-6 text-md-end text-center mb-20">
                    <div class="d-flex align-items-center justify-content-center justify-content-md-end">
                        <p class="text-lg-bold neutral-0 d-inline-block mr-10">Follow us</p>
                        <div class="box-socials-footer d-inline-block">
                            <a class="icon-socials icon-instagram" href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20" fill="none">
                                    <path d="M13.9146 1.6665H6.93127C3.89793 1.6665 2.0896 3.47484 2.0896 6.50817V13.4832C2.0896 16.5248 3.89793 18.3332 6.93127 18.3332H13.9063C16.9396 18.3332 18.7479 16.5248 18.7479 13.4915V6.50817C18.7563 3.47484 16.9479 1.6665 13.9146 1.6665ZM10.4229 13.2332C8.6396 13.2332 7.1896 11.7832 7.1896 9.99984C7.1896 8.2165 8.6396 6.7665 10.4229 6.7665C12.2063 6.7665 13.6563 8.2165 13.6563 9.99984C13.6563 11.7832 12.2063 13.2332 10.4229 13.2332ZM15.3563 5.73317C15.3146 5.83317 15.2563 5.92484 15.1813 6.00817C15.0979 6.08317 15.0063 6.1415 14.9063 6.18317C14.8063 6.22484 14.6979 6.24984 14.5896 6.24984C14.3646 6.24984 14.1563 6.1665 13.9979 6.00817C13.9229 5.92484 13.8646 5.83317 13.8229 5.73317C13.7813 5.63317 13.7563 5.52484 13.7563 5.4165C13.7563 5.30817 13.7813 5.19984 13.8229 5.09984C13.8646 4.9915 13.9229 4.90817 13.9979 4.82484C14.1896 4.63317 14.4813 4.5415 14.7479 4.59984C14.8063 4.60817 14.8563 4.62484 14.9063 4.64984C14.9563 4.6665 15.0063 4.6915 15.0563 4.72484C15.0979 4.74984 15.1396 4.7915 15.1813 4.82484C15.2563 4.90817 15.3146 4.9915 15.3563 5.09984C15.3979 5.19984 15.4229 5.30817 15.4229 5.4165C15.4229 5.52484 15.3979 5.63317 15.3563 5.73317Z" fill="white"/>
                                </svg>
                            </a>
                            <a class="icon-socials icon-facebook" href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20" fill="none">
                                    <path d="M18.7563 13.4915C18.7563 16.5248 16.9479 18.3332 13.9146 18.3332H12.9229C12.4646 18.3332 12.0896 17.9582 12.0896 17.4998V12.6915C12.0896 12.4665 12.2729 12.2748 12.4979 12.2748L13.9646 12.2498C14.0813 12.2415 14.1813 12.1582 14.2063 12.0415L14.4979 10.4498C14.5229 10.2998 14.4063 10.1582 14.2479 10.1582L12.4729 10.1832C12.2396 10.1832 12.0563 9.99985 12.0479 9.77485L12.0146 7.73317C12.0146 7.59984 12.1229 7.48318 12.2646 7.48318L14.2646 7.44984C14.4063 7.44984 14.5146 7.34152 14.5146 7.19985L14.4813 5.19983C14.4813 5.05816 14.3729 4.94984 14.2313 4.94984L11.9813 4.98318C10.5979 5.00818 9.49794 6.1415 9.52294 7.52484L9.5646 9.8165C9.57293 10.0498 9.38961 10.2332 9.15628 10.2415L8.15627 10.2582C8.0146 10.2582 7.90628 10.3665 7.90628 10.5082L7.93127 12.0915C7.93127 12.2332 8.0396 12.3415 8.18126 12.3415L9.18127 12.3248C9.41461 12.3248 9.59792 12.5082 9.60626 12.7332L9.68125 17.4832C9.68959 17.9498 9.31459 18.3332 8.84792 18.3332H6.93126C3.89793 18.3332 2.0896 16.5248 2.0896 13.4832V6.50817C2.0896 3.47484 3.89793 1.6665 6.93126 1.6665H13.9146C16.9479 1.6665 18.7563 3.47484 18.7563 6.50817V13.4915Z" fill="white"/>
                                </svg>
                            </a>
                            <a class="icon-socials icon-twitter" href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20" fill="none">
                                    <path d="M12.2847 8.46864L19.5701 0H17.8437L11.5178 7.3532L6.46535 0H0.637939L8.27824 11.1193L0.637939 20H2.36443L9.04472 12.2348L14.3805 20H20.2079L12.2843 8.46864H12.2847ZM9.92005 11.2173L9.14593 10.1101L2.98651 1.29967H5.63831L10.609 8.40994L11.3831 9.51718L17.8445 18.7594H15.1927L9.92005 11.2177V11.2173Z" fill="white"/>
                                </svg>
                            </a>
                            <a class="icon-socials icon-be" href="#">
                                <svg width="21" height="15" viewbox="0 0 21 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M8.82393 10.736L13.9225 7.78881L8.82393 4.84165V10.736ZM20.1803 3.04389C20.308 3.50561 20.3964 4.12451 20.4554 4.91042C20.5242 5.69633 20.5536 6.37418 20.5536 6.96361L20.6126 7.78881C20.6126 9.94024 20.4554 11.5219 20.1803 12.5337C19.9347 13.4179 19.3649 13.9877 18.4808 14.2333C18.0191 14.361 17.1742 14.4494 15.8775 14.5083C14.6004 14.5771 13.4313 14.6066 12.3507 14.6066L10.7887 14.6655C6.67251 14.6655 4.10848 14.5083 3.09662 14.2333C2.21247 13.9877 1.64269 13.4179 1.39709 12.5337C1.26938 12.072 1.18097 11.4531 1.12203 10.6672C1.05326 9.8813 1.02379 9.20345 1.02379 8.61402L0.964844 7.78881C0.964844 5.63739 1.12203 4.05575 1.39709 3.04389C1.64269 2.15974 2.21247 1.58996 3.09662 1.34436C3.55834 1.21665 4.4032 1.12823 5.69995 1.06929C6.97705 1.00052 8.14609 0.971052 9.22671 0.971052L10.7887 0.912109C14.9049 0.912109 17.4689 1.06929 18.4808 1.34436C19.3649 1.58996 19.9347 2.15974 20.1803 3.04389Z" fill=""></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/inc/header.html
{% load static %}

<header class="header sticky-bar header-home-2 border-0">
    <div class="container-fluid background-body">
        <div class="main-header">
            <div class="header-left">
                <div class="header-logo">
                    <a class="d-flex" href="{% url 'base:home' %}">
                        <img class="light-mode" alt="SFA" src="{% static 'img/logo/logo-green.png' %}" style="width: 100px" />
                        <img class="dark-mode" alt="SFA" src="{% static 'img/logo/logo-green.png' %}" style="width: 100px" />
                    </a>
                </div>
                <div class="header-nav">
                    <nav class="nav-main-menu">
                        <ul class="main-menu">
                            <li>
                                <a href="{% url 'base:home' %}" class="fw-bold">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'base:about' %}" class="fw-bold">About Us</a>
                            </li>
                            
                           
                            <li>
                                <a href="{% url 'base:contact' %}" class="fw-bold">Contact Us</a>
                            </li>
                            <li>
                                <a href="{% url 'base:services' %}" class="fw-bold">Services</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="header-right">
                    {% if user.is_authenticated %}
                        <div class="d-none d-xxl-inline-block align-middle mr-15">
                            <a class="btn btn-signin neutral-1000" href="#">
                                <svg class="mb-1" xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12" fill="none">
                                    <path d="M1 12C1 12 0 12 0 11C0 10 1 7 6 7C11 7 12 10 12 11C12 12 11 12 11 12H1ZM6 6C6.79565 6 7.55871 5.68393 8.12132 5.12132C8.68393 4.55871 9 3.79565 9 3C9 2.20435 8.68393 1.44129 8.12132 0.87868C7.55871 0.316071 6.79565 0 6 0C5.20435 0 4.44129 0.316071 3.87868 0.87868C3.31607 1.44129 3 2.20435 3 3C3 3.79565 3.31607 4.55871 3.87868 5.12132C4.44129 5.68393 5.20435 6 6 6Z" fill="#101010" />
                                </svg>
                                Dashboard
                            </a>
                            <a class="btn btn-signin background-brand-2 text-dark" href="#">
                                Sign Out
                            </a>
                        </div>
                    {% else %}
                        <div class="d-none d-xxl-inline-block align-middle mr-15">
                            <a class="btn btn-signin neutral-1000" href="{% url 'base:login' %}">
                                <svg class="mb-1" xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12" fill="none">
                                    <path d="M1 12C1 12 0 12 0 11C0 10 1 7 6 7C11 7 12 10 12 11C12 12 11 12 11 12H1ZM6 6C6.79565 6 7.55871 5.68393 8.12132 5.12132C8.68393 4.55871 9 3.79565 9 3C9 2.20435 8.68393 1.44129 8.12132 0.87868C7.55871 0.316071 6.79565 0 6 0C5.20435 0 4.44129 0.316071 3.87868 0.87868C3.31607 1.44129 3 2.20435 3 3C3 3.79565 3.31607 4.55871 3.87868 5.12132C4.44129 5.68393 5.20435 6 6 6Z" fill="#101010" />
                                </svg>
                                Sign in
                            </a>
                            <a class="btn btn-signin background-brand-2 text-dark" href="{% url 'base:register' %}">
                                Sign Up
                            </a>
                        </div>
                    {% endif %}
                    <div class="burger-icon burger-icon-white">
                        <span class="burger-icon-top"></span>
                        <span class="burger-icon-mid"> </span>
                        <span class="burger-icon-bottom"> </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="mobile-header-active mobile-header-wrapper-style perfect-scrollbar button-bg-2">
    <div class="mobile-header-wrapper-inner">
        <div class="mobile-header-logo">
            <a class="d-flex" href="{% url 'base:home' %}">
                <img class="light-mode" alt="SFA" src="{% static 'img/logo/logo-green.png' %}" />
                <img class="dark-mode" alt="SFA" src="{% static 'img/logo/logo-green.png' %}" />
            </a>
            <div class="burger-icon burger-icon-white"></div>
        </div>

        <div class="mobile-header-content-area">
            <div class="perfect-scroll">
                <div class="mobile-menu-wrap mobile-header-border">
                    <nav>
                        <ul class="mobile-menu font-heading">
                            <li>
                                <a href="{% url 'base:home' %}" class="fw-bold">Home</a>
                            </li>
                            <li>
                                <a href="#" class="fw-bold">About Us</a>
                            </li>
                            <li>
                                <a href="#" class="fw-bold">Nannies</a>
                            </li>
                            <li>
                                <a href="#" class="fw-bold">Jobs</a>
                            </li>
                            <li>
                                <a href="#" class="fw-bold">Contact Us</a>
                            </li>
                            {% if user.is_authenticated %}
                                <li>
                                    <a href="#" class="fw-bold">Dashboard</a>
                                </li>
                                <li>
                                    <a href="#" class="fw-bold">Sign Out</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="{% url 'base:login' %}" class="fw-bold">Sign In</a>
                                </li>
                                <li>
                                    <a href="{% url 'base:register' %}" class="fw-bold">Sign Up</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

templates/inc/job-sidebar.html
<div class="content-left order-lg-first">
    <div class="sidebar-left border-1 background-body">
        <div class="box-filters-sidebar">
            <div class="block-filter border-1">
                <h6 class="text-lg-bold item-collapse neutral-1000">Categories</h6>
                <div class="box-collapse scrollFilter">
                    <ul class="list-filter-checkbox">
                        {% for code, name in job_categories %}
                            <li>
                                <a href="#" class="text-sm-medium">
                                    {{ name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar-left border-1 background-body">
        <div class="box-filters-sidebar">
            <div class="block-filter border-1">
                <h6 class="text-lg-bold item-collapse neutral-1000">Job Status</h6>
                <div class="box-collapse scrollFilter">
                    <ul class="list-filter-checkbox">
                        {% for status_code, status_name in job_statuses %}
                            <li>
                                <a href="#" class="text-sm-medium">
                                    {{ status_name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

templates/inc/user-sidebar.html
<div class="col-xl-3 col-lg-4">
    <div class="card user-sidebar mb-4">
        <div class="card-header user-sidebar-header">
            <div class="profile-content rounded-pill">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="d-flex align-items-center justify-content-center py-2">
                        <img src="https://static.vecteezy.com/system/resources/thumbnails/005/129/844/small_2x/profile-user-icon-isolated-on-white-background-eps10-free-vector.jpg" alt="image" class="img-fluid avatar avatar-lg rounded-circle me-3">
                        <div>
                            <p class="fw-bold fs-5">{{ request.user.name }} ({{ request.user.role }})</p>
                            <span class="fs-14 text-gray-6">Since {{ request.user.created_at|date }}</span>
                        </div>
                    </div>
                    <div>
                        <div class="d-flex align-items-center justify-content-center">
                            <a href="{% url 'auth:profile' %}" class="p-1 rounded-circle align-items-center justify-content-center btn-edit">
                                <i class="fi fi-rr-pencil fs-7"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body user-sidebar-body">
            <ul class="dashboard-sidebar-menu">
                {% if user.role == 'Client' %}
                    <li class="py-2">
                        <a href="{% url 'base:dashboard' %}">
                            <i class="fi fi-rr-dashboard"></i>
                            Dashboard
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getJobListings' %}">
                            <i class="fi fi-rr-briefcase me-1"></i> 
                            Job Listing
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getJobApplicants' %}">
                            <i class="fi fi-rr-users-alt me-1"></i> 
                            Applicants
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getHireApplications' %}">
                            <i class="fi fi-rr-calendar me-1"></i> 
                            Hire Applications
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'auth:profile' %}">
                            <i class="fi fi-rr-user-md me-1"></i> 
                            My Profile
                        </a>
                    </li>
                {% elif user.role == 'Nanny' %}
                    <li class="py-2">
                        <a href="{% url 'base:dashboard' %}">
                            <i class="fi fi-rr-dashboard"></i>
                            Dashboard
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getJobApplications' %}">
                            <i class="fi fi-rr-Booking me-1"></i> 
                            My Applicants
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getNannyHireApplications' %}">
                            <i class="fi fi-rr-calendar me-1"></i> 
                            Hire Applications
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'auth:profile' %}">
                            <i class="fi fi-rr-user-md me-1"></i> 
                            My Profile
                        </a>
                    </li>
                {% else %}
                    <li class="py-2">
                        <p>
                            You are not authorized to view navigation links.
                        </p>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>